spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.247.181:3306/rn_direct_payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rn
    password: Z9&K9h2R

    #oracle配置
    #    driver-class-name: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@192.168.40.132:1521:xe
    #    username: oracle
    #    password: 123456
    #SQLServer配置
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.40.132:1433;DatabaseName=lejing_job
    #    username: sqlserver
    #    password: 123456
    #PostgreSQL配置
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://192.168.40.132:5432/sonarqube
    #    username: postgres
    #    password: 123456
